
name: DevSecOps-Pipeline

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  security-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
# --- NEW: Set up Node.js Environment ---
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*' # Use a stable Node.js version

# --- NEW: Install Dependencies ---
      - name: Install Dependencies
        run: npm install

      # --- SAST with Semgrep ---
#      - name: Run Semgrep (SAST)
#        uses: returntocorp/semgrep-action@v1
#        with:
#          config: "p/ci"

      # --- SCA with OWASP Dependency Check ---
      - name: Run OWASP Dependency Check (SCA)
        uses: dependency-check/Dependency-Check_Action@main
        id: Depcheck
        with:
          project: 'NodeApp'
          path: '.'
          format: 'HTML'
          out: 'reports'
          args: '--exclude **/passwordProtected.zip --exclude **/arbitraryFileWrite.zip --exclude **/videoExploit.zip'
      # --- DAST with OWASP ZAP ---
#      - name: Run OWASP ZAP Baseline Scan (DAST)
#        uses: zaproxy/action-baseline@v0.9.0
#        with:
#          target: "http://zero.webappsecurity.com/"
#          cmd_options: "-r zap-report.html"

      # --- Upload Reports ---
      - name: Upload Security Reports
        uses: actions/upload-artifact@master
        with:
          name: security-reports
          path: ${{github.workspace}}/reports
