name: SAST Scan with SonarCloud

on: [push, pull_request]

jobs:
  sonarcloud:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install


      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v5.0.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=juice-shop
            -Dsonar.organization=faizaladdp
            -Dsonar.sources=.
            -Dsonar.exclusions=**/node_modules/**,**/test/**,**/frontend/**,**/data/**,**/uploads/**