name: SAST Scan with SonarCloud
on: [push, pull_request]

jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: SonarCloud Scan (SAST only)
        uses: SonarSource/sonarqube-scan-action@v5.0.0
        env:
          SONAR_TOKEN: 83ab569fd53e464dc24fcd93ec50df562380c0ca
        with:
          args: >
            -Dsonar.projectKey=juice-shop
            -Dsonar.organization=faizaladdp
            -Dsonar.sources=.
            -Dsonar.exclusions=**/node_modules/**,**/test/**,**/frontend/**,**/data/**,**/uploads/**