name: DevSecOps-Pipeline

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  security-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      # --- SAST with Semgrep ---
      - name: Run Semgrep (SAST)
        uses: returntocorp/semgrep-action@v1
        with:
          config: "p/ci"

      # --- SCA with OWASP Dependency Check ---
      - name: Run OWASP Dependency Check (SCA)
        uses: dependency-check/Dependency-Check_Action@main
        with:
          project: "NodeApp"
          path: "."
          format: "HTML"
          out: "dependency-check-report"

      # --- DAST with OWASP ZAP ---
      - name: Run OWASP ZAP Baseline Scan (DAST)
        uses: zaproxy/action-baseline@v0.9.0
        with:
          target: "http://juice-shop.herokuapp.com"
          cmd_options: "-r zap-report.html"

      # --- Upload Reports ---
      - name: Upload Security Reports
        uses: actions/upload-artifact@v3
        with:
          name: security-reports
          path: |
            dependency-check-report
            zap-report.html
